### ISSUE TITLE
Editor highlights are not as shown on screenshots

### ISSUE THREAD

**Issue by inosik** [llatigid/Pushkin-is-White-Theme#1]
Without any selected text:

![code_2017-05-12_09-24-27](https://cloud.githubusercontent.com/assets/11393003/25987571/e1bfd39e-36f4-11e7-9243-62c794c95e50.png)

With selected text:

![code_2017-05-12_09-24-51](https://cloud.githubusercontent.com/assets/11393003/25987586/ecfbcbc8-36f4-11e7-809c-c96f35a55254.png)

**Comment by jsfag** [comment]
Hello. The highlight line looks weird because the editor has default **"editor.renderLineHighlight": "line"**. In the theme pictures it is set to **"gutter"**.
In fact, according to the idea of the theme, the editor must invert the colour from the inside, but it's not able to do that (yet).

![2017-05-12 1](https://cloud.githubusercontent.com/assets/3107471/25991644/8c4473d8-3736-11e7-9907-c3f28ac547eb.png)

**Comment by inosik** [comment]
Thanks, setting `editor.renderLineHighlight` to `gutter` solves this.
